name: Dispatch Workflow

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'Enter your username'
        required: true
        default: 'Elle'
      favorite_color:
        description: 'Enter your favorite color'
        required: true
        default: 'blue'

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      username: ${{ steps.output_inputs.outputs.username }}
      favorite_color: ${{ steps.output_inputs.outputs.favorite_color }}
    steps:
      - name: Output Inputs
        id: output_inputs
        run: |
          echo "::set-output name=username::${{ github.event.inputs.username }}"
          echo "::set-output name=favorite_color::${{ github.event.inputs.favorite_color }}"
  
  job2:
    runs-on: ubuntu-latest
    needs: job1
    outputs:
      greeting: ${{ steps.generate_greeting.outputs.greeting }}
    steps:
      - name: Generate Greeting
        id: generate_greeting
        run: |
          USERNAME="${{ needs.job1.outputs.username }}"
          FAVORITE_COLOR="${{ needs.job1.outputs.favorite_color }}"
          GREETING="$USERNAME says hello, and favorite color is $FAVORITE_COLOR"
          echo "::set-output name=greeting::$GREETING"

  job3:
    runs-on: ubuntu-latest
    needs: job2
    steps:
      - name: Echo Greeting
        run: echo "${{ needs.job2.outputs.greeting }}"
